# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a30691f7aa478bc958bfff5961b1ca586aa6d73ed29e1100f23d3af7ce277c65677ef3fabb212f920c473e025164b8a078873761e217f18de2d8af586516dbc6

test:
  secret_key_base: f80ad705056059290a5950d0bbcfd3edf52ac9a95302d06db9827bf9489fc395db0af78d1bfc1d68aebf4bf538ad141c8ee4503cdfd65b8025a17fb39ed4619c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
